language: python

sudo: false

python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
env:
  - DJANGO="django>=1.9.0,<1.10.0" REST_FRAMEWORK="djangorestframework>=3.3,<3.4"
  - DJANGO="django>=1.8.0,<1.9.0" REST_FRAMEWORK="djangorestframework>=3.3,<3.4"
install:
  - travis_retry pip install -q $DJANGO $REST_FRAMEWORK "coverage==3.7.1"
  - pip install .
script:
  - coverage run manage.py test
  - coverage report

matrix:
  exclude:
    - python: "3.3"
      env: DJANGO="django>=1.9.0,<1.10.0" REST_FRAMEWORK="djangorestframework>=3.3,<3.4"
  fast_finish: true
