language: python
dist: xenial

python:
  - "3.4"
  - "3.5"
  - "3.6"

install:
  - travis_retry pip install -U six setuptools pip wheel
  - travis_retry pip install -U tox tox-travis tox-venv coverage
script:
  - tox
after_success:
  - coverage report
  - bash <(curl -s https://codecov.io/bash)

matrix:
  include:
    - python: "3.6"
      env: TOXENV="performance"
      script: tox -- -v 2
    - python: "3.6"
      env: TOXENV="warnings"
    - python: "3.6"
      env: TOXENV="isort,lint"

    - python: "3.6"
      env: TOXENV="dist"
      script:
        - python setup.py bdist_wheel
        - rm -r djangorestframework_filters.egg-info
        - tox --installpkg ./dist/djangorestframework_filters-*.whl
        - tox  # test sdist

  allow_failures:
    - env: TOXENV="warnings"
  fast_finish: true
